{{- if .Values.tls.enabled }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-issuer
  labels:
    {{- include "ror-helm-template.labels" . | nindent 4 }}
spec:
  acme:
    server: {{ .Values.acme.server }}
    email: {{ .Values.acme.email }}
    privateKeySecretRef:
      name: issuer-account-key
    solvers:
    - http01:
       ingress:
         class: nginx
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: web-cert
  labels:
    {{- include "ror-helm-template.labels" . | nindent 4 }}
spec:
  dnsNames:
    {{- range .Values.ingress.hosts }}
      - {{ .host }}
    {{- end }}
  secretName: web-cert
  issuerRef:
    name: letsencrypt-issuer
    kind: Issuer
{{- end }}