---
apiVersion: v1
kind: ConfigMap
metadata: 
  name: common
  labels:
    {{- include "ror-helm-template.labels" . | nindent 4 }}
data:
  RAILS_ENV: {{ .Values.app.rails_env }}
  RACK_ENV: {{ .Values.app.rails_env }}
  RAILS_LOG_TO_STDOUT: enabled
  RAILS_SERVE_STATIC_FILES: "true"
  HOST: {{ .Values.app.hostname }}
  LANG: en_US.UTF-8
  {{- if .Values.app.rails_hosts }}
  RAILS_HOSTS: {{ .Values.app.rails_hosts }}
  {{- end }}
  FORCE_SSL: {{ quote .Values.app.force_ssl }}