---
apiVersion: v1
kind: Secret
metadata:
  name: common
  labels:
    {{- include "ror-helm-template.labels" . | nindent 4 }}
data:
{{- with .Values.app }}
  DATABASE_URL:             {{ include "ror-helm-template.database_url" $.Values | b64enc }}
  REDIS_URL:                {{ include "ror-helm-template.redis_url" $.Values | b64enc  }}
  AWS_SES_PASSWORD:         {{ .aws_ses_password | b64enc }}
  AWS_SES_USERNAME:         {{ .aws_ses_username | b64enc }}
  RR_AWS_ACCESS_KEY:        {{ .rr_aws_access_key | b64enc }}
  RR_AWS_SECRET_ACCESS_KEY: {{ .rr_aws_secret_access_key | b64enc }}
  SECRET_KEY_BASE:          {{ .secret_key_base | b64enc }}
{{- end }}