{{- if .Values.app.runMigration }}
apiVersion: batch/v1
kind: Job
metadata:
  name: migrate-{{.Values.image.tag}}
  labels:
    {{- include "ror-helm-template.labels" . | nindent 4 }}
spec:
  template:
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      restartPolicy: Never
      containers:
        - image:  "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: Always
          name: migrate
          args: ["bundle", "exec", "rake", "db:migrate"]
          envFrom:
            - configMapRef:
                name: common
            - secretRef:
                name: common
{{- end }}