apiVersion: apps/v1
kind: Deployment
metadata: 
  name: worker
  labels:
    app: worker
    {{- include "ror-helm-template.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: worker
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["bundle", "exec", "sidekiq"]
        envFrom:
        - configMapRef:
            name: common
        - secretRef:
            name: common